In [0]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
%cd /gdrive/My\ Drive/Secured/QICC/fakeNewsDataset

/gdrive/My Drive/Secured/QICC/fakeNewsDataset


In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
import itertools
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import os

In [0]:
df = pd.DataFrame(columns=['Headline','Description','Domain','Fake/Legit'])
df_test=pd.DataFrame(columns=['Headline','Description','Domain','Fake/Legit'])

In [0]:
df_eval=pd.DataFrame(columns=['Headline','Description','Domain','Fake/Legit'])

In [0]:
import glob
import re
files_train_fake=glob.glob('fake-training/*.txt')
files_train_legit=glob.glob('legit-training/*.txt')

In [0]:
file_eval=glob.glob('fake-news-real-news-eval/*.txt')

In [0]:
#import fake_training_dataset
for file_name in files_train_fake:
  with open(file_name, "r") as f:
    names_list = [l for l in (line.strip() for line in f) if l]
    if len(names_list)>1:
      df=df.append({'Headline':names_list[0],'Description': "".join(names_list[0:]), 'Domain':re.search(r"[a-zA-Z]*",file_name[14:]).group(), 'Fake/Legit':1}, ignore_index=True)
    else:
      df=df.append({ 'Description': names_list[0], 'Domain':re.search(r"[a-zA-Z]*",file_name[14:]).group(), 'Fake/Legit':1},ignore_index=True)

In [0]:
import codecs

In [0]:
for file_name in file_eval:
  with codecs.open(file_name, 'r', encoding='utf-8', errors='ignore')  as f:
    names_list = [l for l in (line.strip() for line in f) if l]
    if len(names_list)>1:
      df_eval=df_eval.append({'Headline':names_list[0],'Description': "".join(names_list[0:])}, ignore_index=True)
    else:
      df_eval=df_eval.append({ 'Description': names_list[0]}, ignore_index=True)

In [0]:
df.head()

Unnamed: 0  ... Fake/Legit
0           0  ...          1
1           1  ...          1
2           2  ...          1
3           3  ...          1
4           4  ...          1

[5 rows x 5 columns]

In [0]:
#import legit_training_dataset
for file_name in files_train_legit:
  with open(file_name, "r") as f:
    names_list = [l for l in (line.strip() for line in f) if l]
    if len(names_list)>1:
      df=df.append({'Headline':names_list[0],'Description': "".join(names_list[0:]), 'Domain':re.search(r"[a-zA-Z]*",file_name[15:]).group(), 'Fake/Legit':0}, ignore_index=True)
    else:
      df=df.append({ 'Description': names_list[0], 'Domain':re.search(r"[a-zA-Z]*",file_name[15:]).group(), 'Fake/Legit':0},ignore_index=True)

In [0]:
files_test_fake=glob.glob('fake-test/*.txt')
files_test_legit=glob.glob('legit-test/*.txt')

In [0]:
#import fake_test_dataset
for file_name in files_test_fake:
  with open(file_name, "r") as f:
    names_list = [l for l in (line.strip() for line in f) if l]
    if len(names_list)>1:
      df_test=df_test.append({'Headline':names_list[0],'Description': "".join(names_list[0:]), 'Domain':re.search(r"[a-zA-Z]*",file_name[10:]).group(), 'Fake/Legit':1}, ignore_index=True)
    else:
      df_test=df_test.append({ 'Description': names_list[0], 'Domain':re.search(r"[a-zA-Z]*",file_name[10:]).group(), 'Fake/Legit':1},ignore_index=True)


#import legit_test_dataset
for file_name in files_test_legit:
  with open(file_name, "r") as f:
    names_list = [l for l in (line.strip() for line in f) if l]
    if len(names_list)>1:
      df_test=df_test.append({'Headline':names_list[0],'Description': "".join(names_list[0:]), 'Domain':re.search(r"[a-zA-Z]*",file_name[11:]).group(), 'Fake/Legit':0}, ignore_index=True)
    else:
      df_test=df_test.append({ 'Description': names_list[0], 'Domain':re.search(r"[a-zA-Z]*",file_name[11:]).group(), 'Fake/Legit':0},ignore_index=True)

In [0]:
X_train,X_test,y_train,y_test = df['Description'], df_test['Description'], df['Fake/Legit'], df_test['Fake/Legit']

In [0]:
#Applying tfidf to the data set
tfidf_vect = TfidfVectorizer(stop_words = 'english')
tfidf_train = tfidf_vect.fit_transform(X_train)
tfidf_test = tfidf_vect.transform(X_test)
tfidf_df = pd.DataFrame(tfidf_train.A, columns=tfidf_vect.get_feature_names())

In [0]:
clf = MultinomialNB() #Applying Naive Bayes

In [0]:
clf.fit(tfidf_train, y_train.astype('int')) # Fit Naive Bayes classifier according to X, y

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [0]:

pred = clf.predict(tfidf_test)                     # Perform classification on an array of test vectors X.
score = metrics.accuracy_score(y_test.astype('int'), pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test.astype('int'), pred)
print(cm)

accuracy:   0.750
[[19  5]
 [ 7 17]]


In [0]:
from sklearn.metrics import classification_report
print('REPORT:')
print(classification_report(y_test.astype(int), pred))

REPORT:
              precision    recall  f1-score   support

           0       0.73      0.79      0.76        24
           1       0.77      0.71      0.74        24

    accuracy                           0.75        48
   macro avg       0.75      0.75      0.75        48
weighted avg       0.75      0.75      0.75        48



In [0]:
tfidf_eval = tfidf_vect.transform(df_eval['Description'])

In [0]:
pred = clf.predict(tfidf_eval)                     # Perform classification on an array of test vectors X.


In [0]:
pred

array([0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1])

In [0]:
df_eval['Fake/Legit']=pd.Series(pred, index=df_eval.index)

Domain Prediction

In [0]:
df=pd.read_csv("training.csv")
df_test=pd.read_csv("test.csv")

In [0]:
X_train,X_test,y_train,y_test = df['Description'], df_test['Description'], df['Domain'], df_test['Domain']

In [0]:
#Applying tfidf to the data set
tfidf_vect = TfidfVectorizer(stop_words = 'english')
tfidf_train = tfidf_vect.fit_transform(X_train)
tfidf_test = tfidf_vect.transform(X_test)
tfidf_df = pd.DataFrame(tfidf_train.A, columns=tfidf_vect.get_feature_names())

In [0]:
clf = MultinomialNB() #Applying Naive Bayes
clf.fit(tfidf_train, y_train) # Fit Naive Bayes classifier according to X, y

pred = clf.predict(tfidf_test)                     # Perform classification on an array of test vectors X.
score = metrics.accuracy_score(y_test, pred)
print("accuracy:   %0.3f" % score)
cm = metrics.confusion_matrix(y_test, pred)
print(cm)

accuracy:   0.771
[[4 0 0 0 0 4]
 [0 8 0 0 0 0]
 [4 0 3 0 1 0]
 [0 0 0 8 0 0]
 [0 0 1 0 7 0]
 [0 0 0 0 1 7]]


In [0]:
from sklearn.metrics import classification_report
print('REPORT:')
print(classification_report(y_test, pred))

REPORT:
              precision    recall  f1-score   support

         biz       0.50      0.50      0.50         8
         edu       1.00      1.00      1.00         8
       entmt       0.75      0.38      0.50         8
       polit       1.00      1.00      1.00         8
      sports       0.78      0.88      0.82         8
        tech       0.64      0.88      0.74         8

    accuracy                           0.77        48
   macro avg       0.78      0.77      0.76        48
weighted avg       0.78      0.77      0.76        48



In [0]:
pred = clf.predict(tfidf_eval)

In [0]:
pred

array(['edu', 'edu', 'edu', 'polit', 'entmt', 'polit', 'polit', 'entmt',
       'sports', 'polit', 'sports', 'sports', 'entmt', 'entmt', 'entmt',
       'entmt', 'polit', 'polit', 'polit', 'polit', 'tech', 'tech',
       'tech', 'tech', 'sports', 'tech', 'tech', 'entmt', 'sports', 'edu',
       'sports', 'sports', 'polit', 'biz', 'polit', 'biz', 'polit', 'biz',
       'polit', 'biz', 'polit', 'polit', 'polit', 'edu', 'edu', 'polit',
       'entmt', 'entmt', 'tech'], dtype='<U6')

In [0]:
df_eval['Domain']=pd.Series(pred, index=df_eval.index)

In [0]:
df_eval.head()

File Name Domain  Fake/Legit
0  asd01.blind.txt    edu           0
1  asd02.blind.txt    edu           1
2  asd03.blind.txt    edu           1
3  asd04.blind.txt  polit           1
4  bsb01.blind.txt  entmt           1

In [0]:
filesl=[]
for i in file_eval:
  filesl.append(i[25:]);


In [0]:
df_eval['File Name']=pd.Series(filesl, index=df_eval.index)

In [0]:
df_eval

Headline  ...        File Name
0   Male teachers preparing to cover down on 'Day ...  ...  asd01.blind.txt
1          Colombia University Busts a Steve Harvey..  ...  asd02.blind.txt
2   Betsy DeVos's Education Hearing Brings Creatio...  ...  asd03.blind.txt
3                          Trump's Uses His Big Brain  ...  asd04.blind.txt
4                                                 NaN  ...  bsb01.blind.txt
5                                                 NaN  ...  bsb02.blind.txt
6   US President Donald Trump called Australian PM...  ...  bsb03.blind.txt
7   An activist involved in anti-government protes...  ...  bsb04.blind.txt
8   Signed autograph of Michael Jordan's 'Basketba...  ...  fgh01.blind.txt
9   SEXIST RORY MCILROY CALLS VOTE FOR FEMALE MEMB...  ...  fgh02.blind.txt
10        Bruno Fernandes de Souza Exonerated at Last  ...  fgh03.blind.txt
11  Lawrence Okolie: Olympian suffers humiliating ...  ...  fgh04.blind.txt
12  Will Smith reunites with Fresh Prince of Bel-A...  ...  gfd01.blind.txt
13         Emma Thompson felt 'too fat' to live in LA  ...  gfd02.blind.txt
14              Brian Cox plays Postman Pat scientist  ...  gfd03.blind.txt
15  Pharrell the musical: Coming to a screen near you  ...  gfd04.blind.txt
16  Pence: Congress wasn't ready to repeal, replac...  ...  jhg01.blind.txt
17  Tax reform the next big ticket item on Trump's...  ...  jhg02.blind.txt
18  Schumer: Trump showed 'basic lack of competenc...  ...  jhg03.blind.txt
19  President Trump climbs into an 18-wheeler and ...  ...  jhg04.blind.txt
20  New Nintendo Switch game console to launch in ...  ...  jkl01.blind.txt
21  Smart phones and tablets banned on all U.S. fl...  ...  jkl02.blind.txt
22  Google computers defeat shows once again nothi...  ...  jkl03.blind.txt
23  Netflix is testing out commercials, and viewer...  ...  jkl04.blind.txt
24  Nintendo Switch game console to launch in Marc...  ...  lkj01.blind.txt
25  Samsung Galaxy Note 7 banned on all U.S. fligh...  ...  lkj02.blind.txt
26  A Google computer victorious over the world's ...  ...  lkj03.blind.txt
27  Netflix is testing a 'Skip Intro' button, and ...  ...  lkj04.blind.txt
28  Basketball 'bible' auction sets sports memorab...  ...  mnb01.blind.txt
29  Rory McIlroy: Muirfield women membership saga ...  ...  mnb02.blind.txt
30        Bruno: Convicted of murdering ex-girlfriend  ...  mnb03.blind.txt
31  Lawrence Okolie: Olympian wins in 20 seconds o...  ...  mnb04.blind.txt
32  Alex Jones Apologizes for Promoting 'Pizzagate...  ...  poi01.blind.txt
33  Banks and Tech Firms Battle Over Something Aki...  ...  poi02.blind.txt
34        California Upholds Auto Emissions Standards  ...  poi03.blind.txt
35     Renegotiate Nafta? Mexicans Say Get On With It  ...  poi04.blind.txt
36   Alex Jones Vindicated in "Pizzagate" Controversy  ...  qwe01.blind.txt
37                            THE BIG DATA CONSPIRACY  ...  qwe02.blind.txt
38  California Surprisingly Lenient on Auto Emissi...  ...  qwe03.blind.txt
39  Mexicans Are Chomping at the Bit to Stop NAFTA...  ...  qwe04.blind.txt
40       Trump's next legislative target:  tax reform  ...  rty02.blind.txt
41           Schumer: Trump total health care buffoon  ...  rty03.blind.txt
42         Presided Trump pretends to be a worker bee  ...  rty04.blind.txt
43  On 'Day Without Women,' Two Districts Cancel S...  ...  ytr01.blind.txt
44  You've Been Accepted to Columbia. Oops, Our Er...  ...  ytr02.blind.txt
45  Trump's Pick for Education Could Face Unusuall...  ...  ytr04.blind.txt
46  Will Smith reunites with Fresh Prince Pals to ...  ...  zxc01.blind.txt
47  Fat shaming kept Emma Thompson out of Los Angeles  ...  zxc02.blind.txt
48              Brian Cox hosts scientist Postman Pat  ...  zxc03.blind.txt

[49 rows x 5 columns]

In [0]:
df_eval=df_eval.drop(columns=['Headline', 'Description'])

In [0]:
df_eval=df_eval[['File Name', 'Domain', 'Fake/Legit']]

In [0]:
df_eval

File Name  Domain  Fake/Legit
0   asd01.blind.txt     edu           0
1   asd02.blind.txt     edu           1
2   asd03.blind.txt     edu           1
3   asd04.blind.txt   polit           1
4   bsb01.blind.txt   entmt           1
5   bsb02.blind.txt   polit           0
6   bsb03.blind.txt   polit           0
7   bsb04.blind.txt   entmt           0
8   fgh01.blind.txt  sports           0
9   fgh02.blind.txt   polit           1
10  fgh03.blind.txt  sports           1
11  fgh04.blind.txt  sports           1
12  gfd01.blind.txt   entmt           1
13  gfd02.blind.txt   entmt           0
14  gfd03.blind.txt   entmt           0
15  gfd04.blind.txt   entmt           0
16  jhg01.blind.txt   polit           1
17  jhg02.blind.txt   polit           0
18  jhg03.blind.txt   polit           1
19  jhg04.blind.txt   polit           1
20  jkl01.blind.txt    tech           1
21  jkl02.blind.txt    tech           0
22  jkl03.blind.txt    tech           1
23  jkl04.blind.txt    tech           1
24  lkj01.blind.txt  sports           1
25  lkj02.blind.txt    tech           0
26  lkj03.blind.txt    tech           0
27  lkj04.blind.txt   entmt           0
28  mnb01.blind.txt  sports           0
29  mnb02.blind.txt     edu           1
30  mnb03.blind.txt  sports           1
31  mnb04.blind.txt  sports           1
32  poi01.blind.txt   polit           0
33  poi02.blind.txt     biz           1
34  poi03.blind.txt   polit           0
35  poi04.blind.txt     biz           1
36  qwe01.blind.txt   polit           0
37  qwe02.blind.txt     biz           1
38  qwe03.blind.txt   polit           0
39  qwe04.blind.txt     biz           1
40  rty02.blind.txt   polit           1
41  rty03.blind.txt   polit           1
42  rty04.blind.txt   polit           1
43  ytr01.blind.txt     edu           0
44  ytr02.blind.txt     edu           0
45  ytr04.blind.txt   polit           1
46  zxc01.blind.txt   entmt           1
47  zxc02.blind.txt   entmt           1
48  zxc03.blind.txt    tech           1

In [0]:
df_eval.to_csv('01Binary_Task1A.csv')